<?php
/**
 * Sync page view.
 *
 * @package Verhant_DPP
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$auto_sync = get_option( 'verhant_auto_sync', false );
?>
<div class="wrap verhant-admin-wrap">
	<h1>
		<img src="<?php echo esc_url( VERHANT_DPP_PLUGIN_URL . 'assets/verhant-logo.svg' ); ?>" alt="Verhant" width="28" height="28" style="vertical-align: middle; margin-right: 8px;" />
		<?php esc_html_e( 'Verhant DPP — Synchronization', 'verhant-dpp' ); ?>
	</h1>

	<div class="verhant-card">
		<h2><?php esc_html_e( 'Import Products to Verhant', 'verhant-dpp' ); ?></h2>
		<p>
			<?php esc_html_e( 'Import your WooCommerce catalog to Verhant to generate Digital Product Passports for your products.', 'verhant-dpp' ); ?>
		</p>
		<p>
			<button type="button" id="verhant-import-btn" class="button button-primary">
				<?php esc_html_e( 'Start Import', 'verhant-dpp' ); ?>
			</button>
		</p>
		<div id="verhant-import-result" style="display: none;"></div>
	</div>

	<div class="verhant-card">
		<h2><?php esc_html_e( 'Export DPP Data to WooCommerce', 'verhant-dpp' ); ?></h2>
		<p>
			<?php esc_html_e( 'Download DPP links generated by Verhant and automatically publish them on your product pages.', 'verhant-dpp' ); ?>
		</p>
		<p>
			<button type="button" id="verhant-export-btn" class="button button-primary">
				<?php esc_html_e( 'Start Export', 'verhant-dpp' ); ?>
			</button>
		</p>
		<div id="verhant-export-result" style="display: none;"></div>
	</div>

	<div class="verhant-card">
		<h2><?php esc_html_e( 'Automatic Synchronization', 'verhant-dpp' ); ?></h2>
		<p>
			<label>
				<input type="checkbox" id="verhant-auto-sync" <?php checked( $auto_sync ); ?> />
				<?php esc_html_e( 'Automatically sync when you save a WooCommerce product.', 'verhant-dpp' ); ?>
			</label>
		</p>
		<div id="verhant-auto-sync-result" style="display: none;"></div>
	</div>
</div>
